server:
  port: 5052

spring:
  application:
    name: mulemind-auth-service

tenant:
  service:
    url: http://localhost:5053


jwt:
  secret: R9P4zGQkN8w9Z4s8f1xH2bKZPq9nFQX5RrQ8sM1eX2A=
  expiration: 43200000 # 1 hour
